### PR TITLE
Fix stealth merge conflict

### PR DESCRIPTION
**Pull request by BillyONeal**
Between https://github.com/microsoft/vcpkg-tool/pull/856 and https://github.com/microsoft/vcpkg-tool/pull/899

### CODE REVIEW

**Review by JavierMatosD — APPROVED** [review]

**Review by vicroms — APPROVED** [review]

**Review by autoantwort — APPROVED** [review]

**Comment by BillyONeal** [comment]
*and* https://github.com/microsoft/vcpkg-tool/pull/889 changing alignment in `ci` output

**Comment by StarGate-One** [comment]
@BillyONeal /cc @autoantwort 
Will this fix the error building vcpkg-tool with commit:
>commit 2f3a6b407e0312c22c0c0dc4b542015f2e2d9ba2 (HEAD -> main, upstream/main, origin/main, origin/HEAD)
>Author: autoantwort <41973254+autoantwort@users.noreply.github.com>
>Date:   Tue Feb 14 21:45:40 2023 +0100
>
>    ci: Don't pull in ports that causes cascades (#856)

with the following error:

>     3>Done Building Project "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default targets) -- FAILED.
>     1>Done Building Project "D:\vcpkg-tool\build\vcpkg.vcxproj" (default targets) -- FAILED.
>
>Build FAILED.
>
>       "D:\vcpkg-tool\build\vcpkg.vcxproj" (default target) (1) ->
>       "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default target) (3) ->
>       (ClCompile target) -> 
>       D:\vcpkg-tool\src\vcpkg\commands.ci.cpp(183,18): error C2039: 'warnings': is not a member of
>       'vcpkg::ActionPlan' [D:\vcpkg-tool\build\vcpkglib.vcxproj]
>
>    0 Warning(s)
>    1 Error(s)
>
>Time Elapsed 00:02:09.05

I can revert the above commit locally and are able to compile/link vcpkg-tool again locally.

I can open an issue ticket if need be?

**Comment by BillyONeal** [comment]
> @BillyONeal /cc @autoantwort 
> 
> (I opened issue ticket in [vcpkg 29662](https://github.com/microsoft/vcpkg/issues/29662))
> 
> Will this fix the error building vcpkg-tool with commit:
> 
> >commit 2f3a6b407e0312c22c0c0dc4b542015f2e2d9ba2 (HEAD -> main, upstream/main, origin/main, origin/HEAD)
> 
> >Author: autoantwort <41973254+autoantwort@users.noreply.github.com>
> 
> >Date:   Tue Feb 14 21:45:40 2023 +0100
> 
> >
> 
> >    ci: Don't pull in ports that causes cascades (#856)
> 
> 
> 
> with the following error:
> 
> 
> 
> >     3>Done Building Project "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default targets) -- FAILED.
> 
> >     1>Done Building Project "D:\vcpkg-tool\build\vcpkg.vcxproj" (default targets) -- FAILED.
> 
> >
> 
> >Build FAILED.
> 
> >
> 
> >       "D:\vcpkg-tool\build\vcpkg.vcxproj" (default target) (1) ->
> 
> >       "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default target) (3) ->
> 
> >       (ClCompile target) -> 
> 
> >       D:\vcpkg-tool\src\vcpkg\commands.ci.cpp(183,18): error C2039: 'warnings': is not a member of
> 
> >       'vcpkg::ActionPlan' [D:\vcpkg-tool\build\vcpkglib.vcxproj]
> 
> >
> 
> >    0 Warning(s)
> 
> >    1 Error(s)
> 
> >
> 
> >Time Elapsed 00:02:09.05
> 
> 
> 
> I can revert the above commit locally and are able to compile/link vcpkg-tool again locally.
> 
> 
> 
> I can open an issue ticket if need be? 
> 
> 
> 
> 

It should be fixed now

**Comment by StarGate-One** [comment]
Thank you.

**Pull request merged**
