### PR TITLE
Colorize multi-triplet dot graphs

### PR DESCRIPTION
**Pull request by dg0yt**
Just https://github.com/microsoft/vcpkg-tool/pull/1371/commits/8361878a4bc4dab9c5dcae6344974e12d76fd160
Depends on (for now, includes) #1369 and #1370.

Example:
~~~
vcpkg depend-info proj:arm64-linux proj tiff[core] --triplet x64-linux-dynamic --dot | dot -Tpng -oimg.png && xdg-open img.png
~~~
Output:
img

### CODE REVIEW

**Comment by autoantwort** [comment]
So non default triplet -> red; default triplet -> black; host triplet -> gray? 
Maybe use blue instead of red, red looks like an error 😅

**Comment by dg0yt** [comment]
> Maybe use blue instead of red, red looks like an error 😅

Done. 
(And there is room for "error", such as "unsupported".)

**Comment by BillyONeal** [comment]
I'm a bit concerned that grey is a bit too close to the background color; I'm worried about accessibility requirements, that sort of thing.

How about DimGray, HTML color \#696969 ?
or perhaps DarkSlateGray, HTML color \#2F4F4F ?

**Review by BillyONeal — APPROVED** [review]
I am happy with the code here pending quibbles over the specific colors and an Ok from our PM team /cc @AugP

**Comment by BillyONeal** [comment]
> I'm a bit concerned that grey is a bit too close to the background color; I'm worried about accessibility requirements, that sort of thing.
> 
> How about DimGray, HTML color #696969 ? or perhaps DarkSlateGray, HTML color #2F4F4F ?

I note that on https://graphviz.org/doc/info/colors.html they use black text on `gray` and white text on `dimgray` and `darkslategray` suggesting that the latter two are more appropriate for contrast against a white background

**Comment by AugP** [comment]
I have no objections to this, assuming it passes our accessibility compliance requirements. @BillyONeal can you confirm if this conforms to our accessibility requirements?

**Comment by dg0yt** [comment]
After some playing with different candidates, I switched to `gray51`. This is the lightest (=most distant from black) gray which is still label with white text (=distant enough from white) on https://graphviz.org/doc/info/colors.html.

img

**Comment by dg0yt** [comment]
FTR all default native requests remain B/W.

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
