### PR TITLE
Exclude CUDNN environment variables in forbidden list

### PR DESCRIPTION
**Pull request by JackBoosY**
According to the official docments:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html
https://github.com/soumith/cudnn.torch/blob/master/cmake/FindCUDNN.cmake

Don't disallow passing these environment variables in Windows.

### CODE REVIEW

**Review by BillyONeal — CHANGES_REQUESTED** [review]
I don't believe this change is correct. Note that we ban these variables on Windows, where there is no cudnn installer. Currently we 'install' it by unzipping it on top of a cuda install.

Is there a specific port this fixes or something?

**Review by ras0219-msft — CHANGES_REQUESTED** [review]
I don't see `CUDNN_ROOT_DIR` documented anywhere in that nvidia page. The `LIB` and `INCLUDE` paths are only mentioned in the section on "... steps to cross-compile cuDNN samples on NVIDIA DRIVE OS for QNX".

Can you find direct, first party document of these variables and how they're intended to be set and used?

**Comment by JackBoosY** [comment]
> Currently we 'install' it by unzipping it on top of a cuda install.

In the latest version, CUDNN is separated from CUDA [1].
And the official document said:
```bash
export QNX_HOST={flash_dir}/toolchains/qnx_toolchain/host/linux/x86_64
export QNX_TARGET={flash_dir}/toolchains/qnx_toolchain/target/qnx7
export HOST_COMPILER=$QNX_HOST/usr/bin/aarch64-unknown-nto-qnx7.1.0-g++
export CUDNN_LIB_PATH=/usr/lib/aarch64-unknown-nto-qnx
export CUDNN_INCLUDE_PATH=/usr/include/aarch64-unknown-nto-qnx
export CUDA_PATH=/usr/local/cuda-safe-11.4/targets/aarch64-qnx
export PATH=$PATH:$QNX_HOST/usr/bin
```
In cmake side, cmake uses the following environment [2]:
```cmake
find_library(CUDNN_LIBRARY 
  NAMES libcudnn.so${__cudnn_ver_suffix} libcudnn${__cudnn_ver_suffix}.dylib ${__cudnn_lib_win_name}
  PATHS $ENV{LD_LIBRARY_PATH} ${__libpath_cudart} ${CUDNN_ROOT_DIR} ${PC_CUDNN_LIBRARY_DIRS} ${CMAKE_INSTALL_PREFIX}
  PATH_SUFFIXES lib lib64 bin
  DOC "CUDNN library." )
```

But I asked another guy, he said CUDNN should be installed into CUDA installation path, so I can close this PR now [3].

[1]. https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#qnx-cross-compiling-set-env-variables
[2]. https://github.com/soumith/cudnn.torch/blob/master/cmake/FindCUDNN.cmake#L123-L127
[3]. https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux
      https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installwindows

**Comment by BillyONeal** [comment]
> > Currently we 'install' it by unzipping it on top of a cuda install.
> 
> In the latest version, CUDNN is separated from CUDA. And the official document said [1]:
> 
> ```shell
> export QNX_HOST={flash_dir}/toolchains/qnx_toolchain/host/linux/x86_64
> export QNX_TARGET={flash_dir}/toolchains/qnx_toolchain/target/qnx7
> export HOST_COMPILER=$QNX_HOST/usr/bin/aarch64-unknown-nto-qnx7.1.0-g++
> export CUDNN_LIB_PATH=/usr/lib/aarch64-unknown-nto-qnx
> export CUDNN_INCLUDE_PATH=/usr/include/aarch64-unknown-nto-qnx
> export CUDA_PATH=/usr/local/cuda-safe-11.4/targets/aarch64-qnx
> export PATH=$PATH:$QNX_HOST/usr/bin
> ```

Yes, but that's talking about behavior of the official NVIDIA maintained apt packages. Yes, on Linux, you need those environment variables. But this PR only affects Windows, not Linux, so I think only what the Windows docs say are relevant, and they suggest unzip-on-top-of-CUDA. I believe it's going to hit in that `find_library` via `__libpath_cudart`.

Do we have an actual user report this is fixing?

**Comment by JackBoosY** [comment]
@BillyONeal Currently I'm working on add Windows support to port CUDNN since its supports expression is `(windows | linux) & x64`.
But first, we should allow to find cudnn's installed files.

**Comment by JackBoosY** [comment]
@BillyONeal Currently I'm working on refactor onnxruntime-gpu and try to install cudnn in Windows.
Since the cudnn's portfile has:
```cmake
find_path(CUDNN_INCLUDE_DIR NAMES cudnn.h cudnn_v8.h cudnn_v7.h
  HINTS ${CUDA_TOOLKIT_ROOT} $ENV{CUDA_PATH} $ENV{CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN} $ENV{CUDNN_ROOT_DIR} /usr/include
  PATH_SUFFIXES cuda/include include)
find_library(CUDNN_LIBRARY NAMES cudnn cudnn8 cudnn7
  HINTS ${CUDA_TOOLKIT_ROOT} $ENV{CUDA_PATH} $ENV{CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN} $ENV{CUDNN_ROOT_DIR} /usr/lib/x86_64-linux-gnu/
  PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64 cuda/lib/x64)
```
I'm curious if these paths are allowed.

**Comment by BillyONeal** [comment]
>try to install cudnn in Windows

We can't do that because NVidia doesn't provide it without asking you to fill out a questionnaire :(. That's why if you look at our provisioning scripts for it right now we have to grab it from an internal Azure Storage account: https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/create-image.ps1#L24

>Since the cudnn's portfile has:
>I'm curious if these paths are allowed.

CUDA_TOOLKIT_ROOT_DIR is allowed:

https://github.com/microsoft/vcpkg-tool/blob/48be135568c3930571adb03ff1632b8c159c2787/src/vcpkg/base/system.process.cpp#L347

**Comment by JackBoosY** [comment]
At least https://github.com/microsoft/vcpkg/pull/23768 works fine when we update CUDA to the next version.

**Pull request closed without merging**
