### PR TITLE
post build check: Always allow .pc files in lib/pkgconfig and debug/lib/pkgconfig

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes https://github.com/microsoft/vcpkg/issues/29661

### CODE REVIEW

**Comment by Neumann-A** [comment]
Maybe emit a msg that it could be moved to share/pkgconfig ?

**Comment by dg0yt** [comment]
> Maybe emit a msg that it could be moved to share/pkgconfig ?

Better not. Safe the noise when the file is in a valid location.

**Comment by Neumann-A** [comment]
> Better not. Safe the noise when the file is in a valid location.

Maybe only in `--debug` then ?

**Comment by BillyONeal** [comment]
> > Better not. Safe the noise when the file is in a valid location.
> 
> Maybe only in `--debug` then ?

I don't think there's much value in debug only post build checks. Particularly when you can just find them with grep et al. later if you want.

I'm going to merge this because it fixes tool release blockers. Thanks!

**Comment by Neumann-A** [comment]
> Particularly when you can just find them with grep et al. later if you want.

I cannot grep through files I dont have, however I can make CI run in debug mode ;)

**Comment by BillyONeal** [comment]
>I cannot grep through files I dont have, however I can make CI run in debug mode ;)

We make a txt file with all the files installed for you.
________________________________

**Pull request merged**
