### PR TITLE
Remove cmd_execute_and_stream_data() returned debug message.

### PR DESCRIPTION
**Pull request by BillyONeal**
We have seen no reports of broken subprocess output handling, and this message is very spammy. Given that we still have a few messages that direct end users at --debug that seems reason enough to remove spammy messages like this.

### CODE REVIEW

**Comment by ashlhud** [comment]
This would have been helpful to disambiguate some errors we were seeing with our asset cache tool. +1

**Comment by autoantwort** [comment]
I am against removing this debug statement. I find it super helpful when analyzing why things don't work as expected.

**Comment by BillyONeal** [comment]
> I am against removing this debug statement. I find it helpful when analyzing why things don't work as expected. But I would prefer a human readable time format :D

I think any such cases should be replaced by adding EchoInDebug to the right places rather than discussing return values of ReadFile

**Comment by autoantwort** [comment]
At least on Unix it prints the exit code of the command that failed. And EchoInDebug would be spammy I guess 😅

**Comment by BillyONeal** [comment]
> At least on Unix it prints the exit code of the command that failed.

No, it prints the errno of the `read` call. This 'exit code' is not the child process' exit code.

**Comment by BillyONeal** [comment]
Wait, this is the wrong one...

**Comment by BillyONeal** [comment]
This is not the spam I thought it was; perhaps I already removed it a while ago. Thanks to @autoantwort for pointing this out.

**Pull request closed without merging**
