### PR TITLE
Fix CURL filesystem deadlock with corporate proxy

### PR DESCRIPTION
**Pull request by SoftwareApe**
Prevent CURL hanging up without timeout when connection can't be established. Creating a deadlock on the filesystem when executed behind a proxy.

As requested by @JackBoosY, this is PR https://github.com/microsoft/vcpkg/pull/16499, retargeted to vcpkg-tool. Now with longer timeout.

### CODE REVIEW

**Review by ras0219 — APPROVED** [review]

**Comment by SoftwareApe** [comment]
@ras0219 before merging, @JackBoosY said the file lock should be reset after vcpkg is finished and before the curl call. I think this should be done before merging.

**Comment by JackBoosY** [comment]
That should be what @ras0219-msft said.

**Comment by ras0219-msft** [comment]
I think this is a good change even without resetting the file lock -- though we should do that as well.

LGTM, thanks for the PR!

**Comment by SoftwareApe** [comment]
@ras0219-msft I do agree that the merged change already helps, but due to the timeout it may slow down developers, and now not become easy enough to spot anymore (because the failure is *just* slowness, not outright failure). I hope we can somehow still make the actual fix that the filesystem lock isn't held longer than necessary.

**Pull request merged**
