### PR TITLE
increase timeouts for downloads

### PR DESCRIPTION
**Pull request by cenit**
it might ease with errors like https://github.com/microsoft/vcpkg/issues/7207, https://github.com/microsoft/vcpkg/issues/18734

see also https://github.com/microsoft/vcpkg/pull/18171 for related issues with using vcpkg as a download tool

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm not really convinced using a 2 minute timeout is likely to resolve the issue over the existing 1 minute timeout? Keep in mind that timeout is time-to-first-byte. If you get not a single packet back from the server in a whole minute something is probably toast?

**Comment by cenit** [comment]
nope, it's common with some cloud proxies that start with Z that they stop responding for 30 seconds for the last few bytes of your download, while they do whatever they like.
Your download just go timeout in vcpkg (not in the browsers, or in aria, we can copy/paste their timeout if you prefer) and you are left with a .part file "almost" complete (everything apart the last few kb missing).
This is alleviating the issue completely, but i agree it's not nice to be seen. It works.

**Comment by BillyONeal** [comment]
> Your download just go timeout in vcpkg (not in the browsers, or in aria, we can copy/paste their timeout if you prefer) and you are left with a .part file "almost" complete (everything apart the last few kb missing).

It would surprise me if that would change that then, since all of these timeouts are about starting the download, not anything during the download. The timeouts are only resolve, connect, and send.

**Comment by cenit** [comment]
receive, the last one?

**Comment by BillyONeal** [comment]
> receive, the last one?
 
You're correct, I misread because of the word wrapping 😭

If it's intending to workaround a specific proxy configuration perhaps we should use 0, 60000,  30000, 120000?

I'm a little nervous to mess with timeouts like that because it's a symptom treatment rather than a cause treatment, if you know what I mean, so I think we should be as conservative in what is changed as possible. Other maintainers may have different ideas though....

**Comment by cenit** [comment]
> > receive, the last one?
> 
> You're correct, I misread because of the word wrapping 😭
> 
> If it's intending to workaround a specific proxy configuration perhaps we should use 0, 60000, 30000, 120000?
> 
> I'm a little nervous to mess with timeouts like that because it's a symptom treatment rather than a cause treatment, if you know what I mean, so I think we should be as conservative in what is changed as possible. Other maintainers may have different ideas though....

> i agree it's not nice to be seen. It works.

as i said before, i already agree with you. If anyone has a better solution, for me it would be perfect.
I put 120k everywhere just for consistency, so not to have to come back here again later…

(for the wrap, the original commit was better, but the clang format then complained and i had to make it “wrong” to make test happy)

**Comment by cenit** [comment]
so any news on this front? is this PR considered unacceptable or are you thinking about it?

**Comment by BillyONeal** [comment]
> so any news on this front? is this PR considered unacceptable or are you thinking about it?

I personally am hesitant to sign off due to the aforementioned "seems like addressing a symptom rather than a problem" issues but I'm not "request changes" either. I poked other folks to take a look...

**Comment by strega-nil-ms** [comment]
I mean, if it fixes real issues, I'm not _that_ against it.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
