### PR TITLE
Run msiexec with start /wait

### PR DESCRIPTION
**Pull request by dg0yt**
A potential fix for 
- https://github.com/microsoft/vcpkg/issues/19490 
- https://github.com/microsoft/vcpkg/issues/23284

Cf. https://github.com/microsoft/vcpkg/issues/19490#issuecomment-1053580397, https://devblogs.microsoft.com/setup/waiting-for-msiexec-exe-to-finish/

### CODE REVIEW

**Comment by dg0yt** [comment]
Relavant e2e test still passing:
~~~
[end-to-end-tests.ps1] [14/22] Running suite D:\a\1\s\azure-pipelines\end-to-end-tests-dir\fetch.ps1
D:\a\1\s\build.x86.debug\vcpkg.exe --triplet x86-windows --x-buildtrees-root=D:\a\1\s\build.x86.debug\work\testing\buildtrees --x-install-root=D:\a\1\s\build.x86.debug\work\testing\installed --x-packages-root=D:\a\1\s\build.x86.debug\work\testing\packages --overlay-ports=D:\a\1\s\azure-pipelines/e2e_ports/overlays --overlay-triplets=D:\a\1\s\azure-pipelines/e2e_ports/triplets fetch 7zip --vcpkg-root=D:\a\1\s\build.x86.debug\work\testing
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> D:\a\1\s\build.x86.debug\work\testing\down loads\7z1900-x64.msi
Extracting 7zip...
D:\a\1\s\build.x86.debug\work\testing\down loads\tools\7zip-19.00-windows\Files\7-Zip\7z.exe

**Comment by BillyONeal** [comment]
I believe this is unlikely to change anything about the situation.

**Comment by dg0yt** [comment]
> I believe this is unlikely to change anything about the situation.

At least is should improve error reporting and repeated attempts.

**Comment by BillyONeal** [comment]
> At least is should improve error reporting and repeated attempts.

I don't believe it will, because /c already has the effect here. If we were not waiting for exit things would have been long broken long before now.

**Comment by BillyONeal** [comment]
Some combination of this change and https://github.com/microsoft/vcpkg-tool/pull/397 resulted in us now getting *no* output :(.

Looking at it again I think both changes were wrong and the actual problem is that we don't report the partial read that happens for the last stdout write from the child:

```
Loading dependency information for 187 packages...
[DEBUG] CreateProcessW("D:\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 6124: cmd_execute_and_stream_data() returned 0 after    31460 us
[DEBUG] CreateProcessW("D:\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/a/1/s -DPACKAGES_DIR=D:/packages -DBUILDTREES_DIR=D:/buildtrees -D_VCPKG_INSTALLED_DIR=D:/installed -DDOWNLOADS=D:/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 6124: cmd_execute_and_stream_data() returned 0 after    36684 us
Loading dependency information for 513 packages...
```

Note that ReadFile is getting ERROR_BROKEN_PIPE.

**Comment by dg0yt** [comment]
I think it would help to have a test which checks how errors are handled.

**Comment by BillyONeal** [comment]
> I think it would help to have a test which checks how errors are handled.

If you have ideas on how to write such a test I think we would be all ears.

**Pull request merged**
