### PR TITLE
Remove command `x-history`

### PR DESCRIPTION
**Pull request by Thomas1664**
See https://github.com/microsoft/vcpkg-tool/pull/688#issuecomment-1234703354

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by JackBoosY** [comment]
This will lead to a serious problem: how can the user set the builtin-baseline by querying the commit id corresponding to the version of the port?

**Comment by JackBoosY** [comment]
> > This will lead to a serious problem: how can the user set the builtin-baseline by querying the commit id corresponding to the version of the port?
> 
> Just look up the ID in the version history `versions/<port-first-char>-/<portname>.json` ?

I don't think users want to flip through the version history instead of using a command to get this value.
For non-manifest mode, users also encounter this problem.

**Comment by dg0yt** [comment]
> > This will lead to a serious problem: how can the user set the builtin-baseline by querying the commit id corresponding to the version of the port?
> 
> Just look up the ID in the version history `versions/<port-first-char>-/<portname>.json` ?

The commit ID is not *in the file*. To get this ID, you need `git blame versions/<port-first-char>-/<portname>.json`.

**Comment by BillyONeal** [comment]
@JackBoosY ,

@vicroms @ras0219-msft @valeriaconde @JavierMatosD @markle11m and I discussed this today at our PR review meeting, with the following observations:

* This command existed only to prepopulate the version database, and would have been a `z-` command had that convention existed at the time.
* We don't believe that the right approach is for someone to set a baseline by looking for particular port versions. In particular, there are lots of versions that are available from before when baselines existed.
* Even if this exists, we believe only major "groups" of ports are practical use cases here, like boost or qt. There may be correct ways to make this work, like explicitly documenting when we changed these, but that doesn't justify keeping this git based implementation.
* If we get concrete customer use cases that need this, we can bring it back, but we need that concrete customer use case.

**Comment by MonicaLiu0311** [comment]
@BillyONeal 
Here is a concrete customer use case, please pay attention: https://github.com/microsoft/vcpkg/issues/27451

**Pull request merged**
