### PR TITLE
CMakeLists.txt: Make generate-message-map target always available

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes https://github.com/microsoft/vcpkg-tool/pull/773#discussion_r1067535315

### CODE REVIEW

**Comment by BillyONeal** [comment]
As I mentioned in the other comment, I don't believe it is correct to create a CMake target that is not functional. You need artifacts development to be on to produce the localized messages for artifacts.

**Comment by autoantwort** [comment]
Why? The file `ce/ce/locales/messages.json` is checked in and is not changed if I do only non artifacts development.

**Comment by autoantwort** [comment]
I tested this locally and it works totally fine. I don't get where it is supposed to break?

**Comment by BillyONeal** [comment]
@JavierMatosD Did you hook up the thing which embeds the artifacts messages into the same json or did I miss something?

**Comment by autoantwort** [comment]
> Did you hook up the thing which embeds the artifacts messages into the same json or did I miss something?

No this is still the case.  
`x-generate-default-message-map` reads `ce/ce/locales/messages.json` and combines it with the messages in the vcpkg-tool code and writes the result to `locales/messages.json`. 

But when I only change the messages in the vcpkg-tool code I can run `x-generate-default-message-map` to get the updated `locales/messages.json` without touching artifacts development. So why should the cmake custom target unable to do the exact same?

**Comment by JavierMatosD** [comment]
@autoantwort and @BillyONeal I did not intend to check in the artifacts JSON file. That is why it is guarded by ```VCPKG_ARTIFACTS_DEVELOPMENT```. However, by keeping it checked in, users can contribute to localization without the need for additional tools like Node, NPM, or Rush.

**Pull request merged**
