### PR TITLE
Manifests: Remove support for declaring features as lists

### PR DESCRIPTION
**Pull request by autoantwort**
It is not used and not described in the docs. I used `vcpkg format-manifest --all` with the new version and it doesn't reported a wrong file.

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by autoantwort** [comment]
Only rebased

**Comment by strega-nil-ms** [comment]
I'm okay with this; it's mostly a back-compat feature. I would appreciate a diagnostic, though.

**Comment by autoantwort** [comment]
I don't know what you mean exactly with a diagnostic, but it seems that it is not used in the vcpkg repo since https://github.com/microsoft/vcpkg/commit/0fec1340eba828e95c489796eb0c7a4330120686

**Comment by strega-nil-ms** [comment]
@autoantwort oh given that it's from before registries, I don't have a problem removing it personally; needs a discussion anyways tho
By diagnostic, I mean checking for arrays specifically and printing a special error message about it.

**Comment by autoantwort** [comment]
Ok, then I will wait for the result of your internal discussion.

**Comment by BillyONeal** [comment]
We want a second opinion from @ras0219 but we see no problems with merging this.

**Review by ras0219-msft — APPROVED** [review]
This would break the following port versions:

- `abseil` version `2020-03-03#7`
- `blend2d` versions `beta_2020-07-31` and `beta_2020-07-09`

it seems that the other packages actually never had their `port-version` bumped while they had the unstable features syntax. Because this features syntax was not GA, I think it's acceptable to assume no concern for ports outside the curated repo.

To set precedent: I think breaking 3 specific versions of packages that do not have other special significance (last supported release of some major version of a major package like openssl or boost) is an acceptable cost in pursuit of removing an experimental feature. This does not establish the true upper limit of cost that would be acceptable, only that this case falls below it.

Script used to find them:
```sh
#!/bin/bash

for a in versions/*/*.json
do
    echo $a
    versions=$(jq -r '.versions[]."git-tree"' $a)
    for ver in $versions
    do
        features=$(git show $ver:vcpkg.json 2>/dev/null | jq ".features")
        if [ $? -ne 0 ]; then continue; fi
        if [ "${features:0:1}" == "[" ]
        then
            echo "$ver will be broken:"
            git show $ver:vcpkg.json | jq '{
            name: .name,
            "version-string": ."version-string",
            "version-semver": ."version-semver",
            "version-date": ."version-date",
            version: .version,
            "port-version": ."port-version",
            features: .features
            }'
        fi
    done
done
```

**Comment by strega-nil-ms** [comment]
Given that we have three approvals, merging ahead! Thanks robert

**Pull request merged**
