### PR TITLE
Use unique identifier to match return codes in the output

### PR DESCRIPTION
**Pull request by autoantwort**
This were broken in #397

cc @BillyONeal

### CODE REVIEW

**Comment by autoantwort** [comment]
Otherwise you get this helpful output
```
[DEBUG] 91579: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/brotli/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/brotli_arm64-osx 2>&1)
[DEBUG] 91579: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/bzip2/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/bzip2_arm64-osx 2>&1)
[DEBUG] 91579: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/libb2/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libb2_arm64-osx 2>&1)
[DEBUG] 91579: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/freetype/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/freetype_arm64-osx 2>&1)
[DEBUG] 91579: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/libpng/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libpng_arm64-osx 2>&1)
[DEBUG] 91579: cmd_execute_and_stream_data() returned 0 after    23656 us
[DEBUG] 91579: cmd_execute_and_stream_data() returned 0 after    55455 us
[DEBUG] 91579: cmd_execute_and_stream_data() returned 1 after    55401 us
[DEBUG] 91579: cmd_execute_and_stream_data() returned 0 after    55412 us
[DEBUG] 91579: cmd_execute_and_stream_data() returned 0 after    55511 us
```
Which command failed?

**Comment by BillyONeal** [comment]
Sorry, can you explain what's broken? Using one's own pid in the output for debug messages is the usual standard and this seems to be messing with that...

**Comment by autoantwort** [comment]
My motivation to introduce the number prefix was to map the return codes to popen calls. 
Now you get
```
[DEBUG] 1001: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/brotli/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/brotli_arm64-osx 2>&1)
[DEBUG] 1002: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/bzip2/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/bzip2_arm64-osx 2>&1)
[DEBUG] 1003: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/libb2/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libb2_arm64-osx 2>&1)
[DEBUG] 1004: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/freetype/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/freetype_arm64-osx 2>&1)
[DEBUG] 1005: popen( unzip -qq /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/libpng/arm64-osx.zip -d/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libpng_arm64-osx 2>&1)
[DEBUG] 1001: cmd_execute_and_stream_data() returned 0 after    23656 us
[DEBUG] 1003: cmd_execute_and_stream_data() returned 0 after    55455 us
[DEBUG] 1002: cmd_execute_and_stream_data() returned 1 after    55401 us
[DEBUG] 1005: cmd_execute_and_stream_data() returned 0 after    55412 us
[DEBUG] 1004: cmd_execute_and_stream_data() returned 0 after    55511 us
```
and know that the popen call with the number 1002 failed. Before this change you know that any popen call failed. It gets funny if there are hundreds of them.

**Comment by BillyONeal** [comment]
I see, OK, these are different purposes. The purpose of the existing number is to distinguish output from the outer vcpkg binary / process from output emitted by processes inside. You're trying to distinguish exit codes among different parallel subprocesses.

I can see an argument that this behavior is more useful in general but this isn't really a "bug" per se.

**Comment by autoantwort** [comment]
> You're trying to distinguish exit codes among different parallel subprocesses.

That was the initial purpose in https://github.com/microsoft/vcpkg-tool/commit/195ca1c6367b1e9686cc181bbc19d16246455393.

> I can see an argument that this behavior is more useful in general but this isn't really a "bug" per se.

Yeah it is not a "bug".

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
