### PR TITLE
Fix setting VCPKG_ROOT in the cmd one liner.

### PR DESCRIPTION
**Pull request by BillyONeal**
broken in https://github.com/microsoft/vcpkg-tool/pull/947

Also add checklist for VS insertion.

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Comment by BillyONeal** [comment]
@jcbrill Do you want to submit your proposed fix to https://github.com/microsoft/vcpkg-tool/tree/main/vcpkg-init so you get the credit you deserve as you've effectively already fixed it ?

Thanks! <3

**Comment by BillyONeal** [comment]
The thing I'm used to seeing in batch world is `set X="Y"` which does the wrong here, since that leaves `%X%` with quotes inside. As a result I didn't include quotes here, I didn't know about the ability to quote the whole thing.

In general I violently agree with 'quote all the things' when it comes to batch files and `set` has always been the one exception that didn't do what I expected...

**Comment by jcbrill** [comment]
I'm happy to submit a PR.

Before the PR is submitted, a few tests for `%USERPROFILE%`/`VCPKG_ROOT` and `PATH`/`Z_POWERSHELL_EXE` is order on my end since I was only testing the first two assignments in earnest.  It is expected to work but just want to make verify.

> The thing I'm used to seeing in batch world is set X="Y" which does the wrong here, since that leaves %X% with quotes inside. As a result I didn't include quotes here, I didn't know about the ability to quote the whole thing.

A lesson everyone learns the hard way, myself included.

**Comment by jcbrill** [comment]
@BillyONeal Thank you for allowing me to submit a PR for review.

I appreciate that you took the time to read the post above and to respond. That was very gracious of you.

**Pull request merged**
