### PR TITLE
[vcpkg] format-manifest now accepts port names as arguments

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Comment by strega-nil** [comment]
I would not do it this way; I would alternatively do this: 
[0001-how-I-would-do-this.patch.txt](https://github.com/microsoft/vcpkg-tool/files/6306792/0001-how-I-would-do-this.patch.txt)

however, not sure if my teammates agree; marking requires:discussion.

**Comment by BillyONeal** [comment]
I want to resurrect my https://github.com/microsoft/vcpkg/pull/15809 instead because I had tests in that one. I talked with @strega-nil today and will have a fix for her comments at the time.

**Comment by BillyONeal** [comment]
@autoantwort Do you mind if we close this one and continue discussion in #62?

**Comment by BillyONeal** [comment]
Closing this, see rationale in https://github.com/microsoft/vcpkg/issues/18967

**Pull request closed without merging**
