### PR TITLE
Add VCPKG_DEFAULT_ASSET_SOURCE environment variable

### PR DESCRIPTION
**Pull request by zynfly**
Because WSLENV's directory conversion cannot handle the format of azurls well, I refer to VCPKG_ DEFAULT_ BINARY_ CACHE method added  for directory only VCPKG_DEFAULT_BINARY_CACHE.

### CODE REVIEW

**Comment by BillyONeal** [comment]
The default binary cache exists to give a given machine a binary cache, but it isn't clear that there's a reasonable default for an asset cache, as the downloads directory already behaves like a given machine's asset cache. Thus this seems to double disk space consumption of the downloads directory without delivering a meaningful change to customers.

Notably I think you can get the effect you're looking for by setting the existing [`VCPKG_DOWNLOADS`](https://learn.microsoft.com/vcpkg/users/config-environment#vcpkg_downloads) variable. Can you describe why that is insufficient?

Thanks!

**Comment by zynfly** [comment]
I'm very sorry, as a user of vcpkg, I didn't see VCPKG_DOWNLOADS variable.
I just want multiple wsl environments and my Windows to share a cache, after all, accessing GitHub in China is too slow.

**Comment by BillyONeal** [comment]
> I'm very sorry, as a user of vcpkg,

Nothing to be sorry about, we're happy that people care enough to submit contributions!

> I didn't see VCPKG_DOWNLOADS variable.

Makes sense! I'm glad we had something in the box already that helps you.

> I just want multiple wsl environments and my Windows to share a cache, after all, accessing GitHub in China is too slow.

@JackBoosY weren't you running a China mirror of some stuff that might help?

**Comment by JackBoosY** [comment]
> @JackBoosY weren't you running a China mirror of some stuff that might help?

Sorry, my mirror is down due to very few users.

**Comment by zynfly** [comment]
by using VCPKG_ DOWNLOADS ENV variable and WSLENV variable has solved my current problem, but the docker's build process cannot access my cache directory.
Do you have any useful suggestions?
@JackBoosY @BillyONeal

**Comment by BillyONeal** [comment]
That sounds like a docker question, I do not know

**Pull request closed without merging**
