### PR TITLE
Add xbox as a known supports expression term

### PR DESCRIPTION
**Pull request by walbourn**
I can make use of ``VCPKG_DEP_INFO_OVERRIDE_VARS`` in my new xbox community triplets to control when this term is evaluated to true, but for all other triplets vcpkg currently generates:

```
error: Unrecognized identifer name xbox. Add to override list in triplet file.
```

This PR teaches vcpkg about the term and by default it evaluates to false.

### CODE REVIEW

**Comment by walbourn** [comment]
Related to [this PR](https://github.com/microsoft/vcpkg/pull/29210) for new community triplets.

**Comment by BillyONeal** [comment]
@dan-shaw @ras0219-msft @vicroms @markle11m @robotodad @JavierMatosD and I discussed this today.

Thanks for doing the initial digging and testing! We want to make sure that this goes out the door in a relatively fully supported manner, so we're applying an abundance of caution to make sure we do this the right way. The Visual C++ team considers improving gaming support an important tenet right now, and team lead @ras0219-msft is bringing this up with our bosses tomorrow. We want xbox customers to have first class support from our team.

In particular, before shipping this, we want to understand:

1. Whether this is the correct thing to add or whether we should be adding "onecore" instead of / in addition to.
2. Understand the specific expected compiler flags / SDK differences.
3. Understand the need for adding this identifier. (Notably, supports is a 'best effort' thing to avoid people building stuff we know will explode; while we are figuring out how this identifier should be turned on vis a vis `CMAKE_SYSTEM_NAME` or similar we will work with you to achieve your testing goals)

None of this is a problem with this implementation, that is all fine. We just want to make sure everyone is on the same page as to what the identifier means before we have shipped it and thus can't ever change its meaning again.

**Comment by walbourn** [comment]
The **xbox** support term here would indicate support for building with ``WINAPI_FAMILY_GAMES`` as well as avoiding linkage with legacy kernel32.dll.

A **onecore** support term here would be the linkage change only, as there is no specific WINAPI_FAMILY for that scenario.

**Comment by Neumann-A** [comment]
I think this needs a better scaling solution then hardcoding the identifier. Can we make vcpkg simply recognize identifiers as false if it doesn't know about it?

**Comment by BillyONeal** [comment]
> Whether this is the correct thing to add or whether we should be adding "onecore" instead of / in addition to.

As discussed out of band, xbox would imply onecore, but not the reverse, so it makes sense to add a specific identifier for this.

> Understand the specific expected compiler flags / SDK differences.

This is the onecore changes (link with apisets rather than kernel32) as well as some edge cases around WINAPI_FAMILY_GAMING. We will need a toolchain file for this (in $/scripts/toolchains) like UWP and we should have some agreement on the flags to turn this on.

I'm going to merge this as is in order to unblock your further experiments but I think we need agreement on how customers communicate to vcpkg and cmake that they are targeting xbox before we should be going to XBox's customers and telling them to turn this on, if that makes sense.

> Understand the need for adding this identifier. (Notably, supports is a 'best effort' thing to avoid people building stuff we know will explode; while we are figuring out how this identifier should be turned on vis a vis CMAKE_SYSTEM_NAME or similar we will work with you to achieve your testing goals)

I think it has been sufficiently explained now.

**Pull request merged**
