### PR TITLE
Make it possible to run e2e tests without vcpkg.ps1

### PR DESCRIPTION
**Pull request by autoantwort**
I want to run the e2e test but with the vcpkg-tool because I don't build vcpkg.ps1 locally.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Can we instead fix it to deploy vcpkg.ps1 under whatever you're building?

**Comment by BillyONeal** [comment]
To be clear it's just a copy rather than building anything:

https://github.com/microsoft/vcpkg-tool/blob/f67d2aa7ffe0d7b4f182c40c155340c780245261/CMakeLists.txt#L421-L431

**Comment by autoantwort** [comment]
arm64-osx. I only build the target vcpkg via cmake, I just see that there is a target `vcpkg-ps1` that I probably just build too...

**Comment by autoantwort** [comment]
Thank you for the hint. This resolved my "issue" 🤦

**Pull request closed without merging**
