### PR TITLE
Allow embedded port version 0 in version constraint

### PR DESCRIPTION
**Pull request by horenmar**
As per https://github.com/microsoft/vcpkg/issues/28327 there is no good reason to disallow someone specifying port version `0` in the version constraint. This allows it.

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]
Thanks for the PR!

We're currently working on localizing messages across the codebase, so please wait for https://github.com/microsoft/vcpkg-tool/pull/913 to land and adjust this PR accordingly.

This may also have documentation impacts, such as https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md#-dependency-version.

**Comment by BillyONeal** [comment]
I believe this was intentional; similar to the prohibition of leading zeros, the desire is to avoid the potential of "style changes" which would not change the meaning but would change the "SHA" of the content.

I think if we take this change we should take allowing leading zeroes in `"version"` at the same time, as both prohibitions rise from that design goal.

**Comment by horenmar** [comment]
> I think if we take this change we should take allowing leading zeroes in "version" at the same time, as both prohibitions rise from that design goal.

Well I have said that this should work something like a year ago, I still agree.

------

As for style changes, they are already a reality. As far as I know, these two manifests have the same effect.

```json
    {
      "name": "opencv4",
      "version>=": "4.6.0#10",
      "features": [],
      "platform": "!linux"
    },
    {
      "name": "opencv4",
      "version>=": "4.6.0#10",
      "features": ["force-mkl"],
      "platform": "linux"
    },
```

```json
    {
      "name": "opencv4",
      "version>=": "4.6.0#10",
    },
    {
      "name": "opencv4",
      "features": ["force-mkl"],
      "platform": "linux"
    },
```

We currently use mostly the first one, but when updating our `vcpkg.json` we are slowly migrating to the second one, as there is lot less noise (and less places to update the version spec).

And obviously there are comments 😃 


-----

I originally ran into this when scripting automatic updates. We moved our `ffmpeg` port to `5.x`, had a port version of 0, so I serialized it as `5.0.1#0` to be explicit and vcpkg complained. So even if the goal is to avoid these "style changes", it also means that I cannot explicitly specify port version 0, and that vcpkg users have to understand that port version 0 is special and needs to be handled differently.

**Comment by horenmar** [comment]
Speaking of style changes, TIL that these are all identical platform expressions: `x64|x86`, `x64||x86`, `x64, x86`, `x64 or x86`.

**Review by BillyONeal — APPROVED** [review]
After discussion with @ras0219-msft , @AugP , @dan-shaw and @JavierMatosD yesterday I widthdraw my objections about version scheme things. @ras0219-msft  signed up to write a doc describing why this example is different than the leading zeroes case.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
