### PR TITLE
Don't format options table like errors

### PR DESCRIPTION
**Pull request by Thomas1664**
The output of `vcpkg help <command>` was formatted like an error message.

To fix this, I renamed `print_usage` to `usage_for_command` and made it return a `LocalizedString` instead of printing as an error message right away. This allows a more flexible use of this function.

I also changed consumers to print this to stdout in order to be consistent with surrounding messages

### CODE REVIEW

**Comment by BillyONeal** [comment]
Printing this to stderr seems correct, since it is printed when there has been a failure. The resolution of https://github.com/microsoft/vcpkg-tool/pull/1175 was that we wanted to avoid using more than one stream in most cases to avoid synchronization problems in tools that log the streams separately.

**Comment by Thomas1664** [comment]
> Printing this to stderr seems correct, since it is printed when there has been a failure.

This doesn't change with this PR. However, the options table is also used for the help command in which case the rest of the output goes to stdout. This is what this PR fixes.

**Review by BillyONeal — APPROVED** [review]
This LGTM with a few end to end tests added:

* `vcpkg help` output going to `stdout`
* `vcpkg help not-a-topic` output going to `stderr`
* `vcpkg not-a-command` output going to `stderr`
* `vcpkg install --not-a-switch` output going to `stderr`

**Comment by BillyONeal** [comment]
> This doesn't change with this PR. However, the options table is also used for the help command in which case the rest of the output goes to stdout. This is what this PR fixes.

Good point!

**Comment by Thomas1664** [comment]
> * `vcpkg help` output going to `stdout`
> * `vcpkg help not-a-topic` output going to `stderr`
> * `vcpkg not-a-command` output going to `stderr`
> * `vcpkg install --not-a-switch` output going to `stderr`

I want to emphasise that in all 3 error cases all of the output goes to `stdout`. I changed this to `stderr` in 21e9c58.

> This LGTM with a few end to end tests added:

I don't have any experiences with PowerShell or how the end to end tests work.

**Comment by BillyONeal** [comment]
> I don't have any experiences with PowerShell or how the end to end tests work.

I added them

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
