### PR TITLE
[vcpkg] add "vcpkg format-manifest --all" to usage message

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Review by strega-nil — APPROVED** [review]

**Comment by strega-nil** [comment]
This feels like it should be a part of PR #55 or something

**Comment by BillyONeal** [comment]
I observe that we don't list port creation tools (e.g. `vcpkg create`) here since the list is already very long and we expect there to be many more consumers than publishers; probably x-history and all the --x-foo-dir entries should be removed for the same reason?

Tagging requires:discussion: We should either merge this as is or remove the other creator-only options from the output.

**Comment by autoantwort** [comment]
> I observe that we don't list port creation tools (e.g. `vcpkg create`) here since the list is already very long 

Huh? The line above the inserted prints help for `vcpkg create`. 

> We should either merge this as is or remove the other creator-only options from the output.

Maybe add an extra help entry `maintainers` and move maintainers commands there. But imho the current situation is very user/maintainer unfriendly where you have to read several documentation pages to gather the available commands or read the source code to find fundamental commands like `format-manifest` or `x-add-version`.

**Comment by BillyONeal** [comment]
> > I observe that we don't list port creation tools (e.g. `vcpkg create`) here since the list is already very long
> 
> Huh? The line above the inserted prints help for `vcpkg create`.

I am blind? Sorry :(

> > We should either merge this as is or remove the other creator-only options from the output.
> 
> Maybe add an extra help entry `maintainers` and move maintainers commands there. But imho the current situation is very user/maintainer unfriendly where you have to read several documentation pages to gather the available commands or read the source code to find fundamental commands like `format-manifest` or `x-add-version`.

Yeah, I agree.

**Comment by autoantwort** [comment]
Message is now updated.

**Review by BillyONeal — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
