### PR TITLE
[vcpkg] x-add-version now also checks if the manifest file is properly formatted

### PR DESCRIPTION
**Pull request by autoantwort**
Closes microsoft/vcpkg#16880

### CODE REVIEW

**Comment by strega-nil** [comment]
I think this is a good idea, although it needs a `--skip-manifest-checks` or something flag.

**Comment by autoantwort** [comment]
Are the tests using the latest master with microsoft/vcpkg#17120 ?

**Comment by autoantwort** [comment]
> Are the tests using the latest master with [microsoft/vcpkg#17120](https://github.com/microsoft/vcpkg/pull/17120) ?

Or should I add `--skip-formatting-check` [here](https://github.com/microsoft/vcpkg-tool/blob/main/azure-pipelines/end-to-end-tests-dir/versions.ps1#L13)

**Comment by autoantwort** [comment]
This is really needed. Especially now when the PR template asks if you have run `x-add-version`

**Pull request merged**
