### PR TITLE
Add a command-line option to set the default build type.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
As part of fixing microsoft/vcpkg#1626, this PR introduces the `--x-build-type` setting to the `vcpkg install` command. When this setting is specified with a value of `release`, or `debug`, it sets the `VCPKG_DEFAULT_BUILD_TYPE` variable to the CMake script invocation that builds a port.

The `port.cmake` file at microsoft/vcpkg will use this variable to initialize `VCPKG_BUILD_TYPE`, enabling building dependencies in only Release or Debug mode without writing a custom triplet, addressing a long-standing usability issue of vcpkg. For compatibility, if the triplet file sets `VCPKG_BUILD_TYPE` itself, it prevails over `--x-build-type`.

If `--x-build-type` is specified, its value becomes part of the ABI hash. The setting is available only when installing in manifest mode; it would be weird to support it in classic mode, where packages of varied build configurations would coexist under the same triplet.

### CODE REVIEW

**Comment by BillyONeal** [comment]
This is a triplet setting because, in general, the whole universe needs to agree on the value.

```
vcpkg install zlib --x-build-type release
vcpkg install curl
```

will fail, because debug curl is going to need debug zlib, and as far as vcpkg is concerned, debug zlib is installed.

Given that this is a setting the whole world needs to agree on, the right place for it to go *is* the triplet.

As a result I am weakly against this change. I could see an argument for some sort of system that lets common triplet combos be set by the user directly in manifest mode, but that would still be a different triplet, not a specific command line hack for one particular triplet setting.

**Comment by teo-tsirpanis** [comment]
> the whole universe needs to agree on the value

That's why `--x-build-type` works only when installing in manifest mode. The whole universe inside `vcpkg_installed` agrees, doesn't it?

**Comment by Neumann-A** [comment]
I am also against it. Furthermore debug only builds are mostly broken by design.

**Comment by BillyONeal** [comment]
> That's why `--x-build-type` works only when installing in manifest mode. The whole universe inside `vcpkg_installed` agrees, doesn't it?

Yes, but why is `VCPKG_BUILD_TYPE` special among all possible triplet settings?

> I could see an argument for some sort of system that lets common triplet combos be set by the user directly in manifest mode

**Comment by Thomas1664** [comment]
I'm also against this change. This belongs in the triplet file.

**Comment by autoantwort** [comment]
> Given that this is a setting the whole world needs to agree on, the right place for it to go is the triplet.

I mean with per port customization you can also do the same with a triplet file 😄  

Imho it would be nice to have something like a "dynamic triplet" that derives the content of the triplet file from the triplet name, then you also don't need to pollute the triplet folder of the vcpkg repo with all possible combinations of triplets.

**Comment by dg0yt** [comment]
> Imho it would be nice to have something like a "dynamic triplet" that derives the content of the triplet file from the triplet name, then you also don't need to pollute the triplet folder of the vcpkg repo with all possible combinations of triplets.

... if we could transform all inputs into an ABI hashing input...

**Comment by autoantwort** [comment]
> ... if we could transform all inputs into an ABI hashing input... 

Sounds like this could be a problem? The only challenge *could* be to get the same triplet abi as for the file based triplets.

**Comment by Neumann-A** [comment]
> Imho it would be nice to have something like a "dynamic triplet" that derives the content of the triplet file from the triplet name,

you could write such a triplet already. Just include a file with the logic in the triplet instead of copying the code all over the triplets

> then you also don't need to pollute the triplet folder ...

That feature is called overlay triplets is it not ?

**Comment by dg0yt** [comment]
> > ... if we could transform all inputs into an ABI hashing input...
> 
> Sounds like this could be a problem? The only challenge _could_ be to get the same triplet abi as for the file based triplets.

The first challenge is to not get the same ABI hash for all filenames of the dynamic triplet.
https://github.com/microsoft/vcpkg-tool/pull/816 would help...

**Comment by autoantwort** [comment]
> The first challenge is to not get the same ABI hash for all filenames of the dynamic triplet.

It depends how you implement it. But if you generate a file you could simply add a comment to the file and get a different file hash <=> triplet abi.

**Comment by teo-tsirpanis** [comment]
> why is `VCPKG_BUILD_TYPE` special among all possible triplet settings?

@BillyONeal of the options listed in https://learn.microsoft.com/en-us/vcpkg/users/triplets, `VCPKG_BUILD_TYPE` is the one that is the least connected with the actual target platform, and the most likely to vary depending on the circumstances of your build. You don't commonly switch between static or dynamic linkage of the dependencies or the CRT when targeting the same platform, but switching between Release and Debug mode is more commonplace for development versus CI/deployment scenarios. Sure vcpkg aggressively caches its binaries but that's not always possible.

Having to choose between either double the build times to build binaries we won't need, or duplicating our triplet files to have only one line added and forgoing relying on vcpkg's automatic platform detection (our custom triplets have the same name as the default ones) is a current deficiency of vcpkg that I would like to fix.

**Comment by ras0219-msft** [comment]
As has been stated above, `VCPKG_BUILD_TYPE` = `Debug` is fundamentally broken and cannot be realistically fixed. You can achieve something approaching what you'd like by creating a custom triplet with `VCPKG_BUILD_TYPE` = `Release` but setting our compiler flags to "debuggable" flags (`/O0 -g /RTC1 /MDd ....`).

We do believe the current "single configuration" system needs improvement, but we don't think adding this command line flag is the right direction.

Thank you for your contribution!

**Pull request closed without merging**
