### PR TITLE
Update fmt to v11.0.2

### PR DESCRIPTION
**Pull request by tchaikov**
this changeset fixes the build with fmt 11:

- prevent fmt from formatting StringView as a sequence
- include fmt/ranges.h for using fmt::join()

### CODE REVIEW

**Comment by tchaikov** [comment]
@microsoft-github-policy-service agree

**Comment by tchaikov** [comment]
closing. it breaks the build with fmt 10.

**Comment by tchaikov** [comment]
@WangWeiLin-MV in case you are interested.

**Review by BillyONeal — APPROVED** [review]
Thanks!

**Pull request merged**
