### PR TITLE
platform expressions: windows should also be true for mingw systems

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Review by strega-nil-ms — APPROVED** [review]
LGTM

**Comment by ras0219-msft** [comment]
This is testing the limit of what kinds of breaking changes we're willing to merge; this is certainly a very noticeable effect that affects dependency resolution and therefore breaks our contract of "updating the vcpkg tool doesn't change your results".

**Comment by BillyONeal** [comment]
> This is testing the limit of what kinds of breaking changes we're willing to merge; this is certainly a very noticeable effect that affects dependency resolution and therefore breaks our contract of "updating the vcpkg tool doesn't change your results".

That's true, but we never claimed official support for MinGW

**Comment by BillyONeal** [comment]
Related https://github.com/microsoft/vcpkg/pull/18911/

**Comment by autoantwort** [comment]
We then should also document the current behavior

**Comment by autoantwort** [comment]
And `VCPKG_TARGET_IS_WINDOWS` is also true for `MinGW`

**Comment by strega-nil-ms** [comment]
> And `VCPKG_TARGET_IS_WINDOWS` is also true for `MinGW`

Yeah, especially given this, `mingw` should imply `windows`.

**Comment by BillyONeal** [comment]
We talked about this in our team meeting today and consensus was to merge it. Thanks @autoantwort for your contribution!

**Pull request merged**
