### PR TITLE
Fix VersionConstraintUnresolvable message being dropped.

### PR DESCRIPTION
**Pull request by BillyONeal**
In https://github.com/microsoft/vcpkg-tool/pull/936/ , I accidentially forgot the return.

Additional related fixes:

* add [[nodiscard]] to the formatters; note that nodiscard was already in use in strings.h: https://github.com/microsoft/vcpkg-tool/blob/65fcbac58785083569ce63ad4a9255044bf6c35b/include/vcpkg/base/strings.h#L66
* fix a couple of places that were printing a debug message just before "Checks::unreachable" to include that in the Checks::unreachable output instead of a separate debug statement.

Thanks to @Neumann-A for pointing out this bug over Discord and @autoantwort for pointing out which line was messed up after I localized it to #936 .

### CODE REVIEW

**Review by autoantwort — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Comment by autoantwort** [comment]
Btw fixes https://github.com/microsoft/vcpkg/issues/30298

**Comment by BillyONeal** [comment]
I'm about this close to just removing the gcov run because failing legitimate builds on Ubuntu randomly is getting old

**Comment by dg0yt** [comment]
> just removing the gcov run because failing legitimate builds on Ubuntu randomly is getting old

If you think that the gcov step needs some care, you might open an issue and/or ping the contributor.

**Comment by BillyONeal** [comment]
>If you think that the gcov step needs some care, you might open an issue and/or ping the contributor.

It just randomly sometimes crashes. There doesn't seem to be a point in trying to follow up with the folks that own it because we're stuck on an old copy (Ubuntu 20.04) until https://github.com/microsoft/azure-pipelines-agent/issues/3834 gets fixed.

**Comment by dg0yt** [comment]
The failing step was "Analyse test coverage". We could
- make the error non-fatal
- pin a particular version of gcovr

Or find some expert to get coverage from the MSVC builds instead ;-)

**Comment by Neumann-A** [comment]
or use clang-cl ? It also has a coverage flag.

**Comment by BillyONeal** [comment]
> The failing step was "Analyse test coverage". We could
> 
> * make the error non-fatal
> * pin a particular version of gcovr
> 
> Or find some expert to get coverage from the MSVC builds instead ;-)

The thing is that nobody here cares about coverage data to invest effort to try to fix this. If it's "someone showed up and turned this on that might be useful someday and doesn't cause any problems", then sure. But not at a significant reliability cost.

> or use clang-cl ? It also has a coverage flag.

We have very little control over the environment in which these builds run.

**Comment by Neumann-A** [comment]
> We have very little control over the environment in which these builds run.

You dont need control if clang-cl is already installed.... (from #972)
```


Also:
```
FAILED: CMakeFiles/locale-resources.dir/__cmrc_locale-resources/lib.cpp.obj 
C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP  -ID:\a\1\s\build.x64.debug\_cmrc\include /DWIN32 /D_WINDOWS /GR /EHsc /EHsc -FC -permissive- -utf-8 /guard:cf /W4 /sdl -Wmissing-prototypes -Wno-missing-field-initializers /WX /Zi /Ob0 /Od /RTC1 -MTd -std:c++17 /showIncludes /FoCMakeFiles\locale-resources.dir\__cmrc_locale-resources\lib.cpp.obj /FdCMakeFiles\locale-resources.dir\locale-resources.pdb -c -- D:\a\1\s\build.x64.debug\__cmrc_locale-resources\lib.cpp
D:\a\1\s\build.x64.debug\__cmrc_locale-resources\lib.cpp(186,27): error: no previous prototype for function 'get_filesystem' [-Werror,-Wmissing-prototypes]
cmrc::embedded_filesystem get_filesystem() {
                          ^
D:\a\1\s\build.x64.debug\__cmrc_locale-resources\lib.cpp(186,1): note: declare 'static' if the function is not intended to be used outside of this translation unit
cmrc::embedded_filesystem get_filesystem() {
^
static 
1 error generated.
[18/205] Building C object CMakeFiles\tls12-download.dir\src\tls12-download.c.obj
FAILED: CMakeFiles/tls12-download.dir/src/tls12-download.c.obj 
C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo   /DWIN32 /D_WINDOWS -FC -permissive- -utf-8 /guard:cf /W4 /sdl -Wmissing-prototypes -Wno-missing-field-initializers /WX /Zi /Ob0 /Od /RTC1 -MT /showIncludes /FoCMakeFiles\tls12-download.dir\src\tls12-download.c.obj /FdCMakeFiles\tls12-download.dir\ -c -- D:\a\1\s\src\tls12-download.c
D:\a\1\s\src\tls12-download.c(30,1): error: function declared 'noreturn' should not return [-Werror,-Winvalid-noreturn]
}
```


"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\d589167d-2641-4129-b67c-8dfe8838309e.cmd""
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.5.1
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
-- The CXX compiler identification is Clang 15.0.7 with MSVC-like command-line
-- The C compiler identification is Clang 15.0.7 with MSVC-like command-line
```

**Comment by autoantwort** [comment]
It also causes my PRs to fail https://github.com/microsoft/vcpkg-tool/pull/908/checks?check_run_id=12190378060 -.-

**Pull request merged**
