### PR TITLE
Isolate from CLICOLOR variable

### PR DESCRIPTION
**Pull request by dg0yt**
Issue: https://github.com/microsoft/vcpkg/issues/20430#issuecomment-964666576.
Reference: https://bixense.com/clicolors/

### CODE REVIEW

**Comment by dg0yt** [comment]
Hm, I would have expected a failure.

**Comment by BillyONeal** [comment]
I think https://github.com/microsoft/vcpkg-tool/pull/261/files#diff-973f1dc6adc2047e0b47db8396cfa9a9fd4d3a7dde08fbc2747b1cdf7e6619e1R20 happens to go around the problematic bit?

**Comment by dg0yt** [comment]
As I did in the `CLICOLOR_FORCE` PR before:
The first commit was to verify that setting the variable breaks things so that a change is covered by the test.
A second commit would bring the fix.
This worked for CLICOLOR_FORCE but doesn't seem to work for `CLICOLOR`.

I could add unsetting the variable anyway, but there is no point in testing.

As an alternative and clean solution, we might leave the user's variables untouched and rather use `file(WRITE ...)` instead of `message(...)`.

**Comment by BillyONeal** [comment]
It doesn't seem like it should hurt anything to set the variable.

**Comment by dg0yt** [comment]
> It doesn't seem like it should hurt anything to set the variable.

I don't understand. With `CLICOLOR_FORCE`, we *unset* the variable in order to fix a particular use case, reading hashes from cmake output. We may also need to *unset* `CLICOLOR`.
However, it seems to me that this is not the right implementation. The variables are set because the user more or less explicity wants to (force) color output from the build systems. So IMO the proper fix is to change vcpkg so that "the particular use case" is independent of these variables. With the CLICOLOR_FORCE test know to be effective, it should be possible to safely rewrite the current behaviour.

**Comment by BillyONeal** [comment]
Given that https://github.com/microsoft/vcpkg-tool/pull/290 has landed should we close this? I agree a better fix would be to avoid stdout here

**Comment by dg0yt** [comment]
Obsolete.

**Pull request closed without merging**
