### PR TITLE
Grammar Updates

### PR DESCRIPTION
**Pull request by krishnathanki**
few Grammer Updates are made

### CODE REVIEW

**Comment by krishnathanki** [comment]
@microsoft-github-policy-service agree [company="{alonfu}"]

**Comment by krishnathanki** [comment]
@microsoft-github-policy-service agree

**Comment by krishnathanki** [comment]
@microsoft-github-policy-service agree company="alonfu"

**Comment by BillyONeal** [comment]
Unfortunately all the edits here are to license text from upstreams or for contracts with layers we are not allowed to edit.

Thanks for the help, but unfortunately we won't be able to take such edits :/

**Pull request closed without merging**
