### PR TITLE
Add a  parameter to tell CE that it's being called from VCPKG.EXE

### PR DESCRIPTION
**Pull request by fearthecowboy**
(or something else would be ok -- just add a double-dash style switch at the end of the whole command `--whatever`)

(I'm assuming that this one-line is how you'd do it )

### CODE REVIEW

**Comment by BillyONeal** [comment]
Should this replace the `--accept-eula`?

Also now that we're MIT licensed for this there really isn't an EULA...

**Comment by BillyONeal** [comment]
(Also, isn't the answer to 'was this called from the entry point' == yes?)

**Review by BillyONeal — APPROVED** [review]

**Comment by fearthecowboy** [comment]
Yeah, you can remove the --accept-eula when you update to the next build of ce.

(and fyi - if you need to add other switches, they should go at the **end** of the command line) if they are before and they are a naked switch and there is an input parameter right after it, it can misinterpret the input parameter as the value for the --switch)

**Comment by fearthecowboy** [comment]
> (Also, isn't the answer to 'was this called from the entry point' == yes?)

Yes

**Comment by BillyONeal** [comment]
> > (Also, isn't the answer to 'was this called from the entry point' == yes?)
> 
> Yes

I'm saying it's strange to have a switch which is functionally always yes but no big deal.

**Comment by BillyONeal** [comment]
> (and fyi - if you need to add other switches, they should go at the **end** of the command line) if they are before and they are a naked switch and there is an input parameter right after it, it can misinterpret the input parameter as the value for the --switch)

Sounds like a bug that should be fixed on the ce side... we shouldn't be adding switches that accept values of that form and ce should be rejecting command lines where some of the input is not processed.

**Pull request merged**
