### PR TITLE
Use system CMake to unpack if available during 7z bootstrap

### PR DESCRIPTION
**Pull request by vicroms**
A user provided CMake can be used to extract vcpkg's copy of CMake during the `downloads/tools` bootstrap process.

The current fallbacks are:
* System32/tar
* User CMake
* 7zip MSI

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm getting really uncomfortable with the castle we're building here. We need a cmake to get a 7z to get a cmake to get a ....

At what point to we just deploy libarchive?

**Comment by vicroms** [comment]
> I'm getting really uncomfortable with the castle we're building here. We need a cmake to get a 7z to get a cmake to get a ....
> 
> At what point to we just deploy libarchive?

That would be a reasonable alternative. This PR is specifically in service of a user running build machines on Windows Server 2012 R2 (no System32/tar.exe) and not enough privilege to run MSI installers.

**Comment by BillyONeal** [comment]
>Server 2012 R2

People running out-of-support OSes makes Bill sad :(. And whatever is making this machine they're using can't put 7z on the box in the first place?

**Comment by BillyONeal** [comment]
What's the system version of CMake they're using? Could we just be more lax and use that all the time (maybe behind a switch?)

**Comment by vicroms** [comment]
> > Server 2012 R2
> 
> People running out-of-support OSes makes Bill sad :(. And whatever is making this machine they're using can't put 7z on the box in the first place?
We still would need to make changes to consider using a system 7z for this bootstrap. I could try modifying the provider to search 7zip in PATH and use it if available. 

> What's the system version of CMake they're using? Could we just be more lax and use that all the time (maybe behind a switch?)
Oldest documented CMake version I could find was 2.6 (from way back in 2008) and that one already had `cmake -E tar ...` so it could be possible to use that.

**Comment by BillyONeal** [comment]
> Oldest documented CMake version I could find was 2.6 (from way back in 2008) and that one already had `cmake -E tar ...` so it could be possible to use that.

I'm not worried about that not existing, I'm trying to find a path here that avoids "building the stack higher"; I'm not comfortable with an outcome that requires bootstrapping ~3 things in a row to go perfectly for the world to be functional. If we need to we need to but I think it's worth the investigation to avoid if possible.

If the customer you're working with deployed something somewhat recent like 3.20 but we look for 3.24, we could give them instructions that would make us just use 3.20 full stop if the ports they want don't care, for example.

**Comment by vicroms** [comment]
> If the customer you're working with deployed something somewhat recent like 3.20 but we look for 3.24, we could give them instructions that would make us just use 3.20 full stop if the ports they want don't care, for example.

What do you think about adding a `<minVersion>` tag to `vcpkgTools.xml`?

**Comment by BillyONeal** [comment]
> What do you think about adding a `<minVersion>` tag to `vcpkgTools.xml`?

version already means min-version by default.

**Review by BillyONeal — APPROVED** [review]
After discussion today that this doesn't add more "servers that have to be up" I'm OK with this.

I would like to see a comment added that describes the intended path for these scenarios:

```
// Windows 10+: system32 tar -> unzip locked cmake -> unpack 7z .7z
// Windows 8.1-, but we find a system CMake: system cmake to unpack -> unzip locked cmake -> unpack 7z .7z
// Windows 8.1-, but no system cmake: msiexec /a 7z msi -> unzip locked cmake -> unpack 7z .7z
```

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
