### PR TITLE
require exact version match for CMake and PowerShell

### PR DESCRIPTION
**Pull request by Be-ing**
CMake is included in the ABI info, so an exact version match is required
for binary caching to work for sharing a cache between machines with
different environments. Refer to the comment in the code for more
details.

### CODE REVIEW

**Comment by Osyotr** [comment]
I can understand why CMake version is tracked, but why is PowerShell? I very much like the idea of having a switch to disable ABI tracking for these tools.

**Comment by Be-ing** [comment]
I think adding another option would be the worst way this could be solved.

> I can understand why CMake version is tracked

Can you explain? I don't understand what that has to do with ABI.

**Comment by Be-ing** [comment]
Could a maintainer please take a look at this? This is holding back Mixxx from switching from `vcpkg archive` to manifest mode, which we are trying to use so we can run Qt5 and Qt6 builds on the same branch while we transition to Qt6.

**Comment by Osyotr** [comment]
> Can you explain? I don't understand what that has to do with ABI.

You are right, it does not. My guess is that it has something to do with how library is consumed (config file generated for specific version etc.)

**Comment by Be-ing** [comment]
Pinging on this again. We have had several new contributors trying to build Mixxx on ARM macOS but not succeeding with the legacy `vcpkg archive` setup. We have had success building with vcpkg manifest mode on ARM macOS, but we cannot merge support for manifest mode until this issue with binary caching is resolved.

**Comment by Be-ing** [comment]
Superseded by #234

**Pull request closed without merging**
