### PR TITLE
Manifest mode: Allow install packages via cli

### PR DESCRIPTION
**Pull request by autoantwort**
Closes https://github.com/microsoft/vcpkg/discussions/19130

### CODE REVIEW

**Comment by ras0219-msft** [comment]
We do want functionality like this, however I believe our plans are to implement this via a separate command (`vcpkg add x` versus `vcpkg install x`).

We are still internally working on the details of how we would want this functionality to work, so sorry in advance that this PR will likely take a while to get useful feedback on.

**Comment by autoantwort** [comment]
Seems that it will be `vcpkg add port x`. I can copy the code to the new `add` command

**Comment by autoantwort** [comment]
I have created #301, but I think that it should also be possible to add packages with `vcpkg install`

**Comment by strega-nil-ms** [comment]
Are you okay with us closing this @autoantwort? We don't want that feature.

**Comment by BillyONeal** [comment]
I'm closing this PR because it's functionality has already been accepted under the name 'add' and there doesn't seem to be support for making install an even more multi-headed thing.

Thanks for your contribution though, after all, it's what landed in add!

**Pull request closed without merging**
