### PR TITLE
Fix CI crash by ensuring the "core" feature is installed for all ports.

### PR DESCRIPTION
**Pull request by BillyONeal**
This is an attempt to fix the crash/regression in the "ci" command caused by https://github.com/microsoft/vcpkg-tool/pull/298

I'm pretty sure this is not a correct fix but it at least makes the ci command seem to match the last known good commit.

### CODE REVIEW

**Comment by JackBoosY** [comment]
So close my PR https://github.com/microsoft/vcpkg-tool/pull/327.

**Comment by ras0219-msft** [comment]
I've opened #331 with a more generalized fix and problem explanation.

**Comment by BillyONeal** [comment]
Closing in favor of https://github.com/microsoft/vcpkg-tool/pull/331

**Comment by BillyONeal** [comment]
Reopening this because I think it may be more correct and want to further discuss with Robert.

**Pull request merged**
