### PR TITLE
ci: Don't pull in ports that causes cascades

### PR DESCRIPTION
**Pull request by autoantwort**
Same goal as #846 but it works in more situations. Fixes https://github.com/microsoft/vcpkg/issues/23490

### CODE REVIEW

**Comment by dg0yt** [comment]
Isn't https://github.com/microsoft/vcpkg/issues/23490 fixed by #846 for the x64-windows to x86 cross-builds? That PR will already remove the unsupported x86 qtwebengine from the initial list of ports, so it will no longer pull in x64 qtwebengine.

If the focus in on additional output, I would prefer to see this implemented on top of my PR.

**Comment by autoantwort** [comment]
> Isn't https://github.com/microsoft/vcpkg/issues/23490 fixed by https://github.com/microsoft/vcpkg-tool/pull/846 for the x64-windows to x86 cross-builds? That PR will already remove the unsupported x86 qtwebengine from the initial list of ports, so it will no longer pull in x64 qtwebengine.

No. It still pulls in x64 qtwebengine because the qt port does support x86 and the qt port depends in qtwebengine and then all dependencies of x86 qtwebengine gets pulled in (also also x64 qtwebengine)

**Review by BillyONeal — APPROVED** [review]
This looks correct to me. Thanks for the fix!

**Comment by BillyONeal** [comment]
@ras0219-msft Do you want a look at this?

**Comment by dg0yt** [comment]
I would assume that we also need debug variants of the pc files.

**Pull request merged**
