### PR TITLE
Fixed crash on non-existent port with version override

### PR DESCRIPTION
**Pull request by dforsten**
Fixes this issue reported in the vcpkg project:
https://github.com/microsoft/vcpkg/issues/36994

The "entry" function does not return an error but an empty RegistryEntry in some situations, needs to be checked for.

An alternative solution would be to refactor all registry implementations to never return an empty RegistryEntry, but an error instead. 
That should be done in a separate issue after this fix is merged.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thank you for the fix, this looks great!

Could you also add an end-to-end test that verifies this behavior and prevents future regressions? It should hopefully be pretty straightforward to extend https://github.com/microsoft/vcpkg-tool/blob/main/azure-pipelines/end-to-end-tests-dir/registries.ps1 to cover this case.

**Comment by BillyONeal** [comment]
I added such a test. I verified that the un-fixed product failed:

test failure evidence

**Review by BillyONeal — APPROVED** [review]

**Comment by dforsten** [comment]
@microsoft-github-policy-service agree

**Comment by BillyONeal** [comment]
Thanks again for your help!

**Comment by dforsten** [comment]
Glad to be of help,
thanks for creating a great tool for the C++ community!

**Pull request merged**
