### PR TITLE
Allow license expressions in features

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes 2. of https://github.com/microsoft/vcpkg/issues/31820#issuecomment-1582173121

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]
I would like to see an added test for what happens when it's bogus SPDX.

**Comment by autoantwort** [comment]
> I would like to see an added test for what happens when it's bogus SPDX.

You mean like https://github.com/microsoft/vcpkg-tool/blob/8c254a5fb6c503615834fc66bd0717664a339a2e/src/vcpkg-test/manifests.cpp#L1173-L1212
I haven't duplicated the tests because the same deserializer was used

**Comment by BillyONeal** [comment]
I mean showing that `parse_spdx_license_expression` is correctly hooked up with any example, not the full blown mess that is every edge case there.

But this has waited long enough, thanks!

**Comment by vicroms** [comment]
We need to update the [manifests reference documentation](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md#feature).

**Comment by autoantwort** [comment]
I have created https://github.com/microsoft/vcpkg-docs/pull/93

**Pull request merged**
